version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: morphological_analysis_api_container
    ports:
      - "8080:80"
    command: python app.py
