version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    command: python app.py
    container_name: japanese_morphological_analysis_api_container
    environment:
      - TZ=Japan
    ports:
      - "8080:80"
    volumes:
      - ./source:/usr/src/source
